In [12]:
import pandas as pd
import os

In [13]:
student_Info_2021_2022 = os.path.join("Student_Info_2021_2022.csv")

In [19]:
student_Info_2021_2022 = pd.read_csv(student_Info_2021_2022)
student_Info_2021_2022.head()

TypeError: argument of type 'method' is not iterable

In [8]:
student_df_2022 = pd.read_csv(student_data_2022,header=7)

In [9]:
student_df_2022.head(30)

,,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Total Students,"193,727",100.0%,"5,402,928",100.0%,"194,607",100.0%,"5,427,370",100.0%
1,Students by Grade:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Early Childhood Education,210,0.1%,"14,290",0.3%,359,0.2%,"21,375",0.4%
3,Pre-Kindergarten,"11,689",6.0%,"222,767",4.1%,"11,746",6.0%,"223,733",4.1%
4,Pre-Kindergarten: 3-year Old,"2,539",1.3%,"33,969",0.6%,"2,556",1.3%,"34,259",0.6%
5,Pre-Kindergarten: 4-year Old,"9,150",4.7%,"188,798",3.5%,"9,190",4.7%,"189,474",3.5%
6,Kindergarten,"14,132",7.3%,"370,054",6.8%,"14,177",7.3%,"371,502",6.8%
7,Grade 1,"14,987",7.7%,"384,494",7.1%,"15,075",7.7%,"386,232",7.1%
8,Grade 2,"14,216",7.3%,"382,008",7.1%,"14,307",7.4%,"383,838",7.1%
9,Grade 3,"15,023",7.8%,"383,078",7.1%,"15,078",7.7%,"384,872",7.1%
10,Grade 4,"15,201",7.8%,"383,959",7.1%,"15,266",7.8%,"386,011",7.1%
11,Grade 5,"15,282",7.9%,"387,945",7.2%,"15,358",7.9%,"389,971",7.2%
12,Grade 6,"12,701",6.6%,"398,640",7.4%,"12,733",6.5%,"400,447",7.4%
13,Grade 7,"13,279",6.9%,"418,486",7.7%,"13,290",6.8%,"418,788",7.7%
14,Grade 8,"13,144",6.8%,"424,287",7.9%,"13,156",6.8%,"424,544",7.8%
15,Grade 9,"17,662",9.1%,"475,437",8.8%,"17,681",9.1%,"475,746",8.8%
16,Grade 10,"12,866",6.6%,"408,393",7.6%,"12,885",6.6%,"408,700",7.5%
17,Grade 11,"12,334",6.4%,"389,034",7.2%,"12,355",6.3%,"389,454",7.2%
18,Grade 12,"11,001",5.7%,"360,056",6.7%,"11,141",5.7%,"362,157",6.7%
19,Ethnic Distribution:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,African American,"42,886",22.1%,"690,999",12.8%,"43,116",22.2%,"694,302",12.8%
21,Hispanic,"119,881",61.9%,"2,850,147",52.8%,"120,330",61.8%,"2,860,754",52.7%
22,White,"18,714",9.7%,"1,420,166",26.3%,"18,840",9.7%,"1,427,241",26.3%
23,American Indian,365,0.2%,"17,944",0.3%,367,0.2%,"18,028",0.3%
24,Asian,"8,634",4.5%,"259,342",4.8%,"8,693",4.5%,"261,788",4.8%
25,Pacific Islander,167,0.1%,"8,443",0.2%,167,0.1%,"8,477",0.2%
26,Two or More Races,"3,080",1.6%,"155,887",2.9%,"3,094",1.6%,"156,780",2.9%
27,Sex:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Female,"95,988",49.5%,"2,640,313",48.9%,"96,310",49.5%,"2,650,563",48.8%
29,Male,"97,739",50.5%,"2,762,615",51.1%,"98,297",50.5%,"2,776,807",51.2%

In [10]:
student_df_2022.isnull()

,,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,False,False,False,False,False,False,False,False,False
1,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
100,False,False,False,True,True,True,True,True,True
101,False,False,False,True,True,True,True,True,True
102,False,False,False,True,True,True,True,True,True
103,False,False,False,True,True,True,True,True,True
104,False,False,False,True,True,True,True,True,True